version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_TRUST_HOST=TRUE
      - AUTH_OKTA_ID=${AUTH_OKTA_ID}
      - AUTH_OKTA_SECRET=${AUTH_OKTA_SECRET}
      - AUTH_OKTA_ISSUER=${AUTH_OKTA_ISSUER}
      - ORIGIN=http://localhost:3000
      - PUBLIC_OKTA_DOMAIN=${PUBLIC_OKTA_DOMAIN}
